### PR TITLE
Migrate from got to phin

### PR DESCRIPTION
**Pull request by ethanent**
- Updated dependencies (+phin, -got)
- Modified code to use phin instead of got

## Purpose of this pull request? 

- [ ] Documentation update
- [ ] Bug fix 
- [x] Enhancement
- [ ] Other, please explain:

## What changes did you make?

This PR is proposing a dependency change, switching from [got](https://www.npmjs.com/package/got) to [phin](https://github.com/ethanent/phin)!

## Is there anything you'd like reviewers to focus on?

phin, with no dependencies, is very lightweight compared to got and weighs in at just 25KB. (A **>98% reduction** from the size of got and its large dependency tree.)

### CODE REVIEW

**Comment by ethanent** [comment]
Note, of course, that changing the target version for tests like this is a bold change. Note that Node.js version 4 would no longer be tested by the CI should my PR take effect!

I feel that in this case the benefits of my PR's proposed change could outweigh any downsides to this change.

**Comment by SBoudrias** [comment]
@sindresorhus any thoughts on that?

**Comment by sindresorhus** [comment]
Funny thing, if you look at the first commit of Got it will be very similar to Phin. That's before reality kicked in and it was used in production for years. HTTP is so much harder than I could ever have imagined, and while small file size is tempting, solving the problem reliably is much more important.

**Comment by ethanent** [comment]
@sindresorhus Could I get a bit more info about why you believe that phin may not be a reliable solution for yo?

**Pull request closed without merging**
