### PR TITLE
Drop `pinkie-promise`.

### LINKED ISSUE #487: Drop `pinkie-promise`.
Promises are natively supported in `node >= 0.12`, which `yo` supports.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
Closes #487.

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
Waiting on #489.
`gulp-mocha` is not recognizing Promise.

**Comment by wtgtybhertgeghgtwtg** [comment]
I think `env` in `.eslintrc` needs to have `es6` set to `true` for `Promise` to be defined.  I can do that, but I do not think that that falls under the scope of this PR.

**Comment by SBoudrias** [comment]
@wtgtybhertgeghgtwtg I think it does, we'll only merge green build :)

**Comment by wtgtybhertgeghgtwtg** [comment]
I will update the `.eslintrc`, but it will still not be green, since the node 0.12 version is failing due to [an issue](https://github.com/SBoudrias/gulp-exclude-gitignore/issues/5) in `gulp-exclude-gitignore`.  Same reason #489 failed.

**Comment by mischah** [comment]
@wtgtybhertgeghgtwtg You can merge `yeoman:master` to get rid of node 0.10 since #489 has landed.

**Comment by mischah** [comment]
@yeoman what about dropping Support for node 0.12 😂 

Since the doctors says:
```
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✖ Node.js version
Your Node.js version is outdated.
Upgrade to the latest version: https://nodejs.org
```

**Comment by wtgtybhertgeghgtwtg** [comment]
Everything is passing except for coverage, which has decreased.

**Comment by mischah** [comment]
Thanks :octocat:

Your PR did it to the master branch and will be included in the next release.

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for your time.
If you were serious about dropping support for 0.12, I would love to help.

**Comment by mischah** [comment]
> If you were serious about dropping support for 0.12

Nah, not yet :see_no_evil:

**Pull request merged**
