### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by slaven-s**
Hi,

I added section "Books" and a link to the Front-End Tooling with Gulp, Bower, and Yeoman written by Stefan Baumgartner for Manning Publications. We believe this book is a great resource and all members of community will benefit from this information. If you find this inappropriate, please let me know where I can publish it.

### CODE REVIEW

**Comment by SBoudrias** [comment]
This should probably go in the resource section of our website.

**Comment by slaven-s** [comment]
Hello Simon,
we would be very happy if you can put this book in the resource section of your website.Thanks,
Slaven,Manning Publications 


     Datuma 22:26 Četvrtak, 27. Kolovoz 2015., Simon Boudrias <notifications@github.com> je napisao:
   

 This should probably go in the resource section of our website.—

**Comment by sindresorhus** [comment]
Open a pull request or issue over at https://github.com/yeoman/yeoman.io and we'll get it added ;)

**Comment by slaven-s** [comment]
Done. Thank you very much ;) 
 


     Datuma 8:15 Petak, 28. Kolovoz 2015., Sindre Sorhus <notifications@github.com> je napisao:
   

 Open a pull request or issue over at https://github.com/yeoman/yeoman.io and we'll get it added ;)—

**Pull request closed without merging**
