### PR TITLE
Warn when running a generator in ~ or /

### PR DESCRIPTION
**Pull request by royalharsh**
https://github.com/yeoman/yo/issues/215
Added warnings if the user is in home directory.

### CODE REVIEW

**Comment by SBoudrias** [comment]
Hi, thanks for sending this out.

The issue here is that that's not really the fix we'd want.

See, if a user want to run inside the home directory, they should be able to. (they might have a dotfile generator for example).

The issue we want to fix is warn the user when a generator changes its root to the home directory. This is done by the generator when a `.yo-rc.json` file is found in a parent directory. The warning should probably goes into `yeoman-generator`.

**Comment by SBoudrias** [comment]
@royalharsh I saw you tried to contact me on IRC. You should try our gitter channel as it'll allow for async communication that is more timezone friendly https://gitter.im/yeoman/yeoman

**Comment by royalharsh** [comment]
@SBoudrias Should I check and warn the user if `.yo-rc.json` is somewhere up the directory tree rather than in the directory where they want the generator to run ?

**Comment by SBoudrias** [comment]
yes, that's the idea.

**Pull request closed without merging**
