### PR TITLE
chore: cache node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**
## Purpose of this pull request? 

- [ ] Documentation update
- [ ] Bug fix 
- [x] Enhancement
- [ ] Other, please explain:

## What changes did you make?

cache node_modules

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks, but it's a bad idea to cache `node_modules`. It causes lots of problems with outdated dependencies. Travis should test what's getting published, that includes using the latest dependency tree.

**Comment by DanielRuf** [comment]
You could have let the issue open ;-) But we can still use the npm cache then =)

**Comment by DanielRuf** [comment]
Also I still did not see any problems with cached node_modules so far.

**Comment by DanielRuf** [comment]
But I guess this is not needed now as we have the lockfile and Travis CI prefers `npm ci` in this case.

**Pull request closed without merging**
