### PR TITLE
Migrate to yeoman-environment 3.x

### PR DESCRIPTION
**Pull request by mshima**
## Purpose of this pull request? 

- [ ] Documentation update
- [ ] Bug fix 
- [ ] Enhancement
- [ ] Other, please explain:

### CODE REVIEW

**Comment by packetstracer** [comment]
I'm gettint an error when executing yo CLI, maybe is due to this update. Could you let me know?

Node v15 (installed with nvm)
Installed yo 
`npm i -g yo`
Getting an error when executing my generator 
`yo my-generator`

`This generator (entities:app) requires yeoman-environment at least 3.0.0-beta.1, current version is 2.10.3`

If I check nvm yo package.json it appears to have dependency instead of ^3.0.0
`"yeoman-environment": "^2.4.0"`

is It possible that dependencies are not set correctly in the yo npm package?

**Comment by mshima** [comment]
@packetstracer downgrade the yeoman-generator dependency to 4.x while yo 4.0.0 isn't officially released.

**Comment by packetstracer** [comment]
Ok, I guess you mean that yo 5.0.0 is not released yet, I got this dependency "yeoman-generator": "^5.0.1" when installing through npm.

Changed to "yeoman-generator": "^4.0.0" in yeoman generator package.json files, and works ok.

Thanks @mshima

**Comment by flo-sch** [comment]
Hi @mshima, is there any rough roadmap for the v4 release? (Some new features to bring in? Need some help?)
I am quite eager to upgrade to yeoman-generator v5 but I would rather wait for a stable version of `yo` before doing so 🙏

**Comment by ericmorand** [comment]
@mshima so basically the latest available `yeoman-generator` package is not working with the latest available `yo` package?

If so, why has it been released?

**Pull request merged**
