### PR TITLE
bump meow to 9.0 to reduce vulnerable dependencies

### PR DESCRIPTION
**Pull request by gyz0072004**
## Purpose of this pull request? 

- [ ] Documentation update
- [x] Bug fix 
- [ ] Enhancement
- [ ] Other, please explain:

## What changes did you make?
Bump the version of meow to the latest non-ESM version to resolve npm audit issues.

## Is there anything you'd like reviewers to focus on?
Would like a published version if the change is OK.

### CODE REVIEW

**Comment by gyz0072004** [comment]
@mshima Could you please take a look on this? Thanks.

**Comment by gyz0072004** [comment]
@mshima Kindly ping. Could you please take a look? Thanks.

**Comment by mshima** [comment]
Sorry for the delay.
I am worried about https://github.com/sindresorhus/meow/releases/tag/v9.0.0 breaking changes.
The kebab parameter change.
I wonder if this will break legacy generators.

**Comment by gyz0072004** [comment]
I got your concern. Then do we have any plan to migrate yo to pure ESM package as a major release? I think some yeoman has done the migration.

**Comment by gyz0072004** [comment]
I'm closing the PR for now.

**Comment by mshima** [comment]
> I got your concern. Then do we have any plan to migrate yo to pure ESM package as a major release? I think some yeoman has done the migration.

Last yo major version had legacy generator issues, so I am very careful about yo changes to avoid angry reactions.
`yo` and `yeoman-enviroment` have quite unique use case. The must have almost 0 breaking changes forever to don't break old generators. They are engines instead of dependencies.

We use a custom cli in JHipster and yeoman-environment has a cli itself (`yoe`).
So I would say that another cli (`@yeoman/cli`) based on yeoman-environment cli support is the easiest way to move forward but as I've said we use custom cli, so I will not lead the task myself.

**Pull request closed without merging**
