### PR TITLE
Upgrade `opn` to `open`

### LINKED ISSUE #619: opn is deprecated, use open instead
**Summary**

[opn](https://www.npmjs.com/package/opn) is deprecated and renamed to [open](https://www.npmjs.com/package/open). But, it isn't compatible with node-js version 6.

### PR DESCRIPTION
**Pull request by LitoMore**
Resolve #619

### CODE REVIEW

**Comment by LitoMore** [comment]
This change requires Node.js 8 or higher. I will make another pull request to target Node.js 8.

**Comment by SBoudrias** [comment]
Can you actually for the Node.js 8 bump into the same PR? I'd prefer we don't break the CI as other people might come by and wish to send PR.

**Comment by LitoMore** [comment]
@SBoudrias No problem.

**Comment by LitoMore** [comment]
I disabled `promise/prefer-await-to-then` temporary. Because we have to fix lots of functions in library and unit test. I think we could do this refactor job in another pull request.

**Comment by SBoudrias** [comment]
Yeah no worries about that rule, it's not really important.

**Pull request merged**
