### PR TITLE
Fixes ParseError

### PR DESCRIPTION
**Pull request by bjdelro**
## Purpose of this pull request? 

- [ ] Documentation update
- [x] Bug fix 
- [ ] Enhancement
- [ ] Other, please explain:

## What changes did you make?
Fixes https://github.com/yeoman/yo/issues/540
- added an isString check on `name` variable to ensure it is a string so that it doesn't fail on the .split.
Used lodash since it's already a dependency. 

## Is there anything you'd like reviewers to focus on?

https://github.com/bjdelro/yo/blob/ec37d54f8dd6ab50d77d2deeaab26db599e77581/lib/routes/home.js#L58

### CODE REVIEW

**Comment by sindresorhus** [comment]
This should be fixed in `fullname` and not here.

**Comment by SBoudrias** [comment]
True enough, @bjdelro would you be good enough to send one over there too?

**Comment by bjdelro** [comment]
@SBoudrias yeah I can do that then this PR can be reverted?

**Comment by SBoudrias** [comment]
@bjdelro yes once it gets fix upstream 😄

**Pull request merged**
